# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$aws\
$nodejs\
$kubernetes\
$line_break\
$character
"""

[character]
success_symbol = "[>](#9ED06C)"
error_symbol = "[>](#FB617E)"

[aws]
symbol = "󰈷 "
style = "#EACB64"
format = "[$symbol($profile)]($style) "

[nodejs]
format = "[$symbol($version)]($style) "

[git_branch]
symbol = " "
style = "#FF6578"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "#F69C5E"
format = "([$all_status$ahead_behind]($style)) "

[directory]
truncate_to_repo = false
truncation_length = 2
truncation_symbol = "…/"
style = "#72CCE8"

[kubernetes]
disabled = false
style = "#BA9CF3"
format = '[$symbol($namespace)]($style)'
