# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

format = "$directory$git_branch$git_status$all"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[line_break]
disabled = true 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[aws]
# disabled = true
symbol = "󰈷 "
style = "yellow"
format = "[$symbol($profile)]($style) "

[git_branch]
symbol = " "
style = "purple"
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "red"
format = "([$all_status$ahead_behind]($style)) "

[terraform]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 2
truncation_symbol = "…/"
style = "cyan"
